<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="86" started-at="2017-03-10T15:20:10Z" finished-at="2017-03-10T15:20:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="86" started-at="2017-03-10T15:20:10Z" finished-at="2017-03-10T15:20:10Z">
      <class name="NEFHAM.NEFHAM.GameTest">
        <test-method status="FAIL" signature="createGame(boolean, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, int, java.lang.String)[pri:0, instance:NEFHAM.NEFHAM.GameTest@6a2bcfcb]" name="createGame" duration-ms="31" started-at="2017-03-10T17:20:10Z" data-provider="createGameData" finished-at="2017-03-10T17:20:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[true]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[math]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[pazzle]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[saleh]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[10/3/2017]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[MCQ]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[What is your goal;h/n/j/p;j]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at NEFHAM.NEFHAM.GameTest.createGame(GameTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createGame -->
        <test-method status="PASS" signature="playGame(java.lang.String, java.lang.String)[pri:0, instance:NEFHAM.NEFHAM.GameTest@6a2bcfcb]" name="playGame" duration-ms="3" started-at="2017-03-10T17:20:10Z" data-provider="playGameData" finished-at="2017-03-10T17:20:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Math;s;Saleh;18/12/2016;MCQ;3;What is your name;a/b/c/d;a;What is your country;m/n/o/p;n;What is your goal;h/n/j/p;j]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[s]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- playGame -->
        <test-method status="FAIL" signature="playGame(java.lang.String, java.lang.String)[pri:0, instance:NEFHAM.NEFHAM.GameTest@6a2bcfcb]" name="playGame" duration-ms="4" started-at="2017-03-10T17:20:10Z" data-provider="playGameData" finished-at="2017-03-10T17:20:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Math;s;Saleh;18/12/2016;MCQ;3;What is your name;a/b/c/d;a;What is your country;m/n/o/p;n;What is your goal;h/n/j/p;j]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[h]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.StringIndexOutOfBoundsException">
            <message>
              <![CDATA[String index out of range: -1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at NEFHAM.Game.playGame(Game.java:142)
	at NEFHAM.NEFHAM.GameTest.playGame(GameTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.StringIndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- playGame -->
      </class> <!-- NEFHAM.NEFHAM.GameTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
